config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'auctions#index'

  resources :auctions, shallow: true do
    patch :publish
    resources :bids, only: [:create]
    resources :watches, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create] do
    resources :watches, only: [:index]
    resources :bids, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/auction.rb
class Auction < ApplicationRecord
  include AASM
  validates_presence_of :title
  validates_presence_of :details

  belongs_to :user
  has_many :bids, dependent: :destroy

  has_many :watches, dependent: :destroy
  has_many :watchers, through: :watches, source: :users

  aasm do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :cancelled
    state :reserve_not_met

    state :draft do
      validates(:title, presence: true, length: { minimum: 3})
      validates(:details, presence: true, length: { minimum: 3})
      validates(:reserve_price, numericality: { greater_than_or_equal_to: 0.1 })
    end

    event :publish do
      transitions from: :draft, to: :published
    end

    event :reserve_has_met do
      transitions from: [:published, :draft], to: :reserve_met
    end

    event :auction_won do
      transitions from: :published, to: :won
    end

    event :cancel do
      transitions from: :published, to: :cancelled
    end

    event :reserve_unmet do
      transitions from: :published, to: :reserve_not_met
    end
  end

  def watched_by?(user)
    watches.exists?(user: user)
  end

  def watch_for(user)
    watches.find_by(user: user)
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action(:find_auction, { only: [:show, :edit, :destroy] })
  before_action(:find_for_publish, { only: :publish })

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user
    @auction.current_price = 0
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @user = :current_user
    @bid = Bid.new
  end

  def index
    #@auctions = Auction.published.order("created_at DESC")
    @auctions = Auction.order(created_at: :desc)
  end

  def destroy
    if @auction.user == current_user
      @auction.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def publish
    if @auction.publish!
      redirect_to auctions_path, notice: "Auction published successfully."
    else
      redirect_to auctions_path, alter: "Auction publishing failed: #{@auction.errors.full_messages}"
    end
  end


  private

  def auction_params
    params.require(:auction).permit([:title, :details, :ends_on, :reserve_price])
  end

  def find_auction
    @auction = Auction.find params[:id]
  end

  def find_for_publish
    @auction = Auction.find params[:auction_id]
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_for @auction do |a| %>
  <div>
    <%= a.label :title %>
    <%= a.text_field :title %>
  </div>
  <div>
    <%= a.label :details %>
    <%= a.text_area :details %>
  </div>
  <div>
    <%= a.label :reserve_price %>
    <%= a.text_area :reserve_price %>
  </div>
  <div>
    <%= a.text_field :ends_on, "data-provide" => 'datepicker' %>
  </div>
  <%= a.submit %>
<% end %>

app/views/auctions/index.html.erb
<h1>All Auctions</h1>

 <% @auctions.each do |a| %>
  <%= link_to a.title, auction_path(a) %>
  <hr>
<% end %>

app/views/auctions/new.html.erb
<h1>Create New Auction</h1>
<%= @auction.errors.full_messages.join(', ') %>

<%= render 'form' %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<p><%= @auction.details %></p>
<p>Ends on: <%= @auction.ends_on %></p>

<% if @auction.aasm_state == 'reserve_not_met' || @auction.aasm_state == 'draft' || @auction.aasm_state == 'published'%>
  <p> <%= @auction.aasm_state %></p>
  <p>Reserve Not Met</p>
<% elsif @auction.aasm_state == 'reserve_met'%>
  <p>Reserve Met</p>
<% end %>

<p>Current Price: <%= @auction.current_price %></p>


<% if user_signed_in? && can?(:manage, @auction) %>
  <% if @auction.aasm_state == 'draft' %>
    <%= link_to "Publish", auction_publish_path(@auction), method: :patch %>
  <% end %>
  <%= link_to 'Delete', auction_path(@auction),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %>
<% end %>

<div>

<% if user_signed_in? && can?(:watch, @auction) %>

  <% if @auction.watched_by?(current_user) %>

    <%= link_to watch_path(@auction.watch_for(current_user)), method: :delete, class: "btn btn-default" do %>

      <span class="glyphicon glyphicon-eye-open"></span>
    <% end %>
     <p>You are watching this auction.</p>
  <% else %>

    <%= link_to auction_watches_path(@auction), method: :post, class: "btn btn-default" do %>

       <span class="glyphicon glyphicon-eye-open"></span>
    <% end %>
     <p>You are not watching this auction.</p>
  <% end %>
<% end %>


<hr>
<% if user_signed_in? && can?(:bid, @auction) && @auction.aasm_state != 'reserve_met' %>
  <%= @bid.errors.full_messages.join(', ') %>
  <%= form_for ([@auction, @bid]) do |b| %>
    <div>
      <%= b.label :bid %>
      <%= b.number_field :bid %>
    </div>
    <%= b.submit %>
  <% end %>
    <hr>
<% end %>
  <h3>Previous Bids</h3>
  <div id='bids'>
     <% @auction.bids.order(created_at: :desc).each do |b| %>
       <p>Bid:<%= b.bid %></p>
       <p>Made by: <%= b.user.full_name %></p>
       <p>Made on: <%= b.created_at.to_date.to_formatted_s(:long)  %></p>
     <% end %>
  </div>